### PR TITLE
Updates from running script

### PR DESCRIPTION
**Pull request by mchowning**
I updated these names on the Google Sheet as having consented as well.

### CODE REVIEW

**Comment by jeffpaul** [comment]
I'm seeing a difference in counts on this one, would @elibud to double check the changes look ok as maybe my eyes are crooked tonight.

**Comment by mchowning** [comment]
There were 2 or 3 (iirc) people who consented a "second" time with this run, so we are recording the comment as "handled" but not adding a "new" consent to the count. 

There was also a comment from someone granting consent (`cristianraiber`) who the script indicated was not a contributor. I have written that down as something I need to follow up on (probably just need to ask them to confirm that they are the same as `cristian-raiber`, but I wanted to see if there was a way for me to confirm that without bugging them again).

Sorry I forgot to mention that in the issue description. I didn't think about how those would make the count appear off.

**Comment by jeffpaul** [comment]
@mchowning to be as accurate and precise as possible with `cristianraiber` we will probably want to check the contributor details as if its `cristian-raiber` that's the correct account then we ideally get them to approve from that account.

**Comment by mchowning** [comment]
Updated with a new run of the script.

> to be as accurate and precise as possible with cristianraiber we will probably want to check the contributor details as if its cristian-raiber that's the correct account then we ideally get them to approve from that account.

👍  I thought maybe this was just a case where they changed their username, but it doesn't appear to be the case (both users exist separately), so I think that you're right that I need to reach out to the user and ask them to approve from the other account. I left a comments on the issue asking both [cristainraiber](https://github.com/WordPress/gutenberg/issues/31893#issuecomment-874937311) and [fritz-c](https://github.com/WordPress/gutenberg/issues/31893#issuecomment-874941849) to follow-up with the account that authored the contributions.

**Comment by jeffpaul** [comment]
I'll also make note tomorrow to ping them outside of GitHub to alert them to the same need in case they are ignoring that GH issue.

**Comment by mchowning** [comment]
> I'll also make note tomorrow to ping them outside of GitHub to alert them to the same need in case they are ignoring that GH issue.

👍 

Is there anything else we need to do to merge this @jeffpaul ?

**Review by jeffpaul — APPROVED** [review]
I'll work to get confirmed approval from alternate/preferred handles for these folks tomorrow

**Pull request merged**
